config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'url_shortens#new'
  post 'url_shortens/get_url' => "url_shortens#shorten_url"
  get 'stats'=>"url_shortens#stats"
  get 'redirect_to'=>"url_shortens#redirect_url_to"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shorten_url.rb
class ShortenUrl < ApplicationRecord
  validates :original_url, format: { with: URL_REGEXP, message: 'You provided invalid URL' }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/url_shortens_controller.rb
class UrlShortensController < ApplicationController
    
    after_action :increment, only: %i[redirect_url_to]

    def new
    end

    def shorten_url
        find_random_characters
        saving_url = ShortenUrl.new
        saving_url.original_url = params[:url]
        saving_url.short_url = shortened_url(@strings)
        saving_url.ip_address = request.remote_ip
        results = Geocoder.search(request.remote_ip)
        saving_url.countries = results.first.country.to_s
        saving_url.save!
        data = {string: shortened_url(@strings),original_string: saving_url.original_url}
        respond_to do |format|
            format.json { render json: data }
        end
    end
    
    def redirect_url_to
        @actual_url = ShortenUrl.find_by_id(params[:id])
        days_active = (Time.now - (@actual_url.created_at)).to_i/86400
        redirect_to @actual_url.original_url if days_active!=30
    end
    def stats
        @urls = ShortenUrl.all
    end

    private

    def increment
        @actual_url.increment!(:total_clicks)
    end

    def find_random_characters
        o = [('a'..'z'),(0..9)].map(&:to_a).flatten
        @strings = (0...5).map { o[rand(o.length)] }.join
    end

    def shortened_url(strings)
        "https://localhost:3000/#{strings}"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_shortens_helper.rb
module UrlShortensHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortnerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url_shortens/new.html.erb
<script>
function isUrlValid(userInput) {
    var res = userInput.match(/(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/g);
    if(res == null)
        return false;
    else
        return true;
}
function shorten_function() {
    if (isUrlValid($("#input_value").val())){
        $.ajax({
            url: '/url_shortens/get_url',
            data: {url: $('#input_value').val()},
            error: function() {
                $('#info').html('<p>Please check it is a valid url</p>');
            },
            success: function(data) {
                $("#info").hide();
                $('#shortened_url').html('<h4>Your Shortned url is</h4><a href='+data.original_string+'>'+data.string+'</a>')
            },
            type: 'POST'
        })
    }
    else{
        $('#info').html('<p>Please check it is a valid url</p>');
    }
}
</script>
<h2>Welcome to localhost:3000</h2>
<div id="info">
</div>
<label>Please enter your url below:</label>
<input type="text" id="input_value">
<button onclick="shorten_function()">Shorten</button>

<div id="shortened_url">
</div>

app/views/url_shortens/stats.html.erb
<h2>Analytics</h2>
<%@urls.each do |url|%>
    <%= url.original_url%>
    <br>
    <a href="<%=redirect_to_path(:id=>url.id) %>"><%= url.short_url%></a>
    <br>
    <label>Total Clicks: </label>
    <%= url.total_clicks%>
    <br>
    <label>Top Countries: </label>
    <%= url.countries%>
    <br>
    <hr>
<%end%>